kotlin.code.style=official

# Configuration should be synced with [/gradle/build-logic/gradle.properties]
org.gradle.caching=true
# Disabled so composite includeBuild of metro-os toolkits can resolve.
org.gradle.isolated-projects=false
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.tooling.parallel=true
